name: chatchat
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.5.6+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_scroll_text: ^0.0.7
  avatar_better: ^0.0.9+5
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  chat_bubbles:
    path: packages/chat_bubbles/
  chewie: ^1.9.2
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.7+1
  event: ^3.1.0
  external_path: 2.0.1
  firebase_admin: ^0.3.0+1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_dotenv: ^5.2.1
  flutter_link_previewer:
    path: packages/flutter_link_previewer/
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.5
  flutter_offline: ^4.0.0
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.17
  gal: ^2.3.1
  gap: ^3.0.1
  google_sign_in: ^6.2.2
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  keyboard_dismisser: ^3.0.0
  king_cache: ^0.0.44
  local_auth: ^2.3.0
  lottie: ^3.3.1
  modal_bottom_sheet: ^3.0.0
  multi_select_flutter: ^4.1.3
  pretty_dio_logger: ^1.4.0
  pub_semver: ^2.1.5
  restart_app: ^1.3.2
  searchable_listview: ^2.16.0
  selectable_search_list: ^0.0.2
  shared_preferences: ^2.5.2
  typesense: ^0.5.2
  url_launcher: ^6.3.1
  zego_uikit_prebuilt_call: ^4.16.24
  zego_uikit_signaling_plugin: ^2.8.11

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/translations/
    - assets/svgs/
    - assets/firebase/
    - .env
